ALTER TABLE weekly_reports
  ADD COLUMN IF NOT EXISTS learned1 TEXT,
  ADD COLUMN IF NOT EXISTS learned2 TEXT,
  ADD COLUMN IF NOT EXISTS learned3 TEXT,
  ADD COLUMN IF NOT EXISTS learned4 TEXT,
  ADD COLUMN IF NOT EXISTS learned5 TEXT;
